<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        @page { margin: 28px; }
        body { font-family: "DejaVu Sans", sans-serif; color: #17202a; font-size: 11px; }
        .header { border-bottom: 3px solid #8cc63f; padding-bottom: 14px; margin-bottom: 18px; }
        .brand-row { border-collapse: collapse; margin-bottom: 3px; }
        .brand-row td { vertical-align: middle; padding: 0; }
        .brand-logo { width: 28px; padding-right: 7px !important; }
        .brand-logo img { display: block; width: 22px; height: auto; }
        .brand { color: #006838; font-size: 11px; font-weight: 700; letter-spacing: 1.6px; text-transform: uppercase; }
        h1 { margin: 4px 0 6px; font-size: 24px; color: #12351f; }
        .muted { color: #667085; }
        .meta { width: 100%; border-collapse: collapse; margin-top: 12px; }
        .meta td { padding: 4px 0; vertical-align: top; }
        .summary { width: 100%; border-collapse: collapse; margin: 14px 0 18px; }
        .summary td { width: 16.66%; padding: 8px; border: 1px solid #dfe8d6; background: #f7fbf2; }
        .summary span { display: block; color: #667085; font-size: 9px; text-transform: uppercase; }
        .summary strong { display: block; margin-top: 3px; font-size: 15px; color: #12351f; }
        .payroll { border: 1px solid #dfe8d6; background: #fbfdf7; padding: 12px; margin-bottom: 16px; }
        .payroll h2 { margin: 0 0 8px; font-size: 14px; color: #12351f; }
        .payroll-grid { width: 100%; border-collapse: collapse; }
        .payroll-grid td { padding: 4px 0; }
        table.data { width: 100%; border-collapse: collapse; }
        table.data th { background: #12351f; color: #fff; padding: 7px 6px; text-align: left; font-size: 9px; }
        table.data td { border-bottom: 1px solid #e7ecdf; padding: 6px; vertical-align: top; }
        .status { font-weight: 700; color: #006838; }
        .late { color: #a15c00; }
        .absent { color: #b42318; }
        .footer { margin-top: 18px; color: #667085; font-size: 9px; text-align: right; }
    </style>
</head>
<body>
    @php
        $summary = $payload['summary'];
        $filters = $payload['filters'];
        $selectedIntern = $payload['selectedIntern'];
        $payroll = $payload['payroll'];
        $statusClass = fn ($status) => $status === 'Tidak Masuk' ? 'absent' : ($status === 'Terlambat' ? 'late' : 'status');
    @endphp

    <div class="header">
        @include('dashboard.attendance.partials.pdf-brand')
        <h1>Attendance Report</h1>
        <!-- <div class="muted">Report absensi berdasarkan data yang tampil pada filter halaman absensi.</div> -->
        <table class="meta">
            <tr>
                <td><strong>Period</strong><br>{{ $filters['from'] }} to {{ $filters['to'] }}</td>
                <td><strong>Intern</strong><br>{{ $selectedIntern ? ($selectedIntern->intern?->txtInternName ?? $selectedIntern->txtEmail) : 'All Intern' }}</td>
                <td><strong>Generated</strong><br>{{ $payload['generatedAt']->format('d M Y H:i') }} WIB</td>
                <td><strong>Generated By</strong><br>{{ $payload['generatedBy'] }}</td>
            </tr>
        </table>
    </div>

    <table class="summary">
        <tr>
            <td><span>Workdays</span><strong>{{ $summary['total'] }}</strong></td>
            <td><span>Present</span><strong>{{ $summary['present'] }}</strong></td>
            <td><span>Late</span><strong>{{ $summary['late'] }}</strong></td>
            <td><span>Absent</span><strong>{{ $summary['absent'] }}</strong></td>
            <td><span>Pending</span><strong>{{ $summary['pending'] }}</strong></td>
            <td><span>Out Warning</span><strong>{{ $summary['clockOutWarnings'] }}</strong></td>
        </tr>
    </table>

    @if ($payroll)
        <div class="payroll">
            <h2>Payroll Snapshot</h2>
            <table class="payroll-grid">
                <tr>
                    <td><strong>Intern</strong><br>{{ $payroll['internName'] }} - {{ $payroll['internType'] }}</td>
                    <td><strong>Salary / Day</strong><br>Rp {{ number_format((float) $payroll['dailySalary'], 0, ',', '.') }}</td>
                    <td><strong>Gross</strong><br>Rp {{ number_format((float) $payroll['grossSalary'], 0, ',', '.') }}</td>
                    <td><strong>Deduction</strong><br>Rp {{ number_format((float) $payroll['deduction'], 0, ',', '.') }}</td>
                    <td><strong>Net Salary</strong><br>Rp {{ number_format((float) $payroll['netSalary'], 0, ',', '.') }}</td>
                </tr>
            </table>
        </div>
    @endif

    <table class="data">
        <thead>
            <tr>
                <th>Date</th>
                <th>Intern</th>
                <th>Type</th>
                <th>Status</th>
                <th>Clock In</th>
                <th>Clock Out</th>
                <th>Salary / Day</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($payload['rows'] as $row)
                <tr>
                    <td>{{ $row['date']->format('d M Y') }}</td>
                    <td>{{ $row['internNo'] }}<br>{{ $row['name'] }}</td>
                    <td>{{ $row['internTypeLabel'] }}</td>
                    <td class="{{ $statusClass($row['status']) }}">{{ $row['status'] }}</td>
                    <td>{{ $row['clockIn'] }}<br><span class="muted">{{ $row['clockInStatus'] ?: '-' }}</span></td>
                    <td>{{ $row['clockOut'] }}<br><span class="muted">{{ $row['clockOutStatus'] ?: '-' }}</span></td>
                    <td>Rp {{ number_format((float) $row['dailySalary'], 0, ',', '.') }}</td>
                </tr>
            @empty
                <tr><td colspan="7">No attendance data on this filter.</td></tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">Generated by Kalbe Internship Monitoring</div>
</body>
</html>
