<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        @page { margin: 18px; }
        body { font-family: "DejaVu Sans", sans-serif; color: #111827; font-size: 8px; }
        .header { border-bottom: 2px solid #8cc63f; padding-bottom: 8px; margin-bottom: 10px; }
        .brand-row { border-collapse: collapse; margin-bottom: 2px; }
        .brand-row td { vertical-align: middle; padding: 0; }
        .brand-logo { width: 24px; padding-right: 6px !important; }
        .brand-logo img { display: block; width: 18px; height: auto; }
        .brand { color: #006838; font-size: 9px; font-weight: 700; letter-spacing: 1.2px; text-transform: uppercase; }
        h1 { margin: 3px 0 4px; color: #12351f; font-size: 17px; }
        .meta { width: 48%; border-collapse: collapse; }
        .meta td { padding: 2px 6px 2px 0; vertical-align: top; }
        .meta td:first-child { width: 78px; font-weight: 800; }
        .layout { width: 100%; border-collapse: collapse; }
        .layout > tbody > tr > td { vertical-align: top; }
        .matrix-wrap { width: 81%; }
        .legend-wrap { width: 19%; padding-left: 12px; }
        table.matrix { width: 100%; border-collapse: collapse; table-layout: fixed; }
        .matrix th, .matrix td { border: 1.4px solid #111827; text-align: center; vertical-align: middle; }
        .matrix th { padding: 5px 3px; font-weight: 800; background: #fff; }
        .matrix td { padding: 4px 2px; height: 20px; }
        .name-col { width: 110px; text-align: left !important; padding-left: 6px !important; }
        .date-col { width: 21px; }
        .recap-col { width: 58px; }
        .money-col { width: 66px; }
        .cell-dot { display: inline-block; width: 18px; height: 18px; border-radius: 50%; line-height: 18px; font-weight: 800; }
        .present { background: #7ed957; }
        .late { background: #ffd95a; }
        .absent { background: #ff5a5f; }
        .wfh { background: #91a7ff; }
        .sick { background: #9be7e4; }
        .permission { background: #bdbdbd; }
        .pending { background: #f2f4f7; color: #667085; }
        .legend h2 { margin: 0 0 7px; font-size: 12px; font-weight: 700; }
        .legend table { width: 100%; border-collapse: collapse; }
        .legend td { padding: 4px 3px; vertical-align: middle; font-size: 10px; }
        .legend-swatch { width: 18px; height: 18px; border-radius: 50%; text-align: center; line-height: 18px; font-size: 8px; font-weight: 800; }
        .footer { margin-top: 8px; color: #667085; font-size: 7px; text-align: right; }
    </style>
</head>
<body>
    @php
        $filters = $payload['filters'];
        $dates = $payload['calendar'];
        $matrixRows = $payload['matrixRows'];
        $months = $dates->groupBy(fn ($date) => $date->format('Y-m'));
        $monthName = fn ($date) => match ((int) $date->format('n')) {
            1 => 'Januari',
            2 => 'Februari',
            3 => 'Maret',
            4 => 'April',
            5 => 'Mei',
            6 => 'Juni',
            7 => 'Juli',
            8 => 'Agustus',
            9 => 'September',
            10 => 'Oktober',
            11 => 'November',
            default => 'Desember',
        }.' '.$date->format('Y');
    @endphp

    <div class="header">
        @include('dashboard.attendance.partials.pdf-brand')
        <h1>Attendance Report Matrix</h1>
        <table class="meta">
            <tr><td>Period</td><td>{{ $filters['from'] }} to {{ $filters['to'] }}</td></tr>
            <tr><td>Generated</td><td>{{ $payload['generatedAt']->format('d M Y H:i') }} WIB</td></tr>
            <tr><td>Generated By</td><td>{{ $payload['generatedBy'] }}</td></tr>
            <tr><td>Intern</td><td>{{ $payload['selectedIntern'] ? ($payload['selectedIntern']->intern?->txtInternName ?? $payload['selectedIntern']->txtEmail) : 'All Intern' }}</td></tr>
        </table>
    </div>

    <table class="layout">
        <tr>
            <td class="matrix-wrap">
                <table class="matrix">
                    <thead>
                        <tr>
                            <th class="name-col">Bulan</th>
                            @foreach ($months as $monthDates)
                                <th class="date-col" colspan="{{ $monthDates->count() }}">{{ $monthDates->first() ? $monthName($monthDates->first()) : '' }}</th>
                            @endforeach
                            <th class="recap-col" rowspan="2">Masuk<br>(WFH/WFO)</th>
                            <th class="recap-col" rowspan="2">Tidak Masuk<br>(Absen/Izin/Sakit)</th>
                            <th class="money-col" rowspan="2">Uang Saku</th>
                        </tr>
                        <tr>
                            <th class="name-col">Tanggal</th>
                            @foreach ($dates as $date)
                                <th class="date-col">{{ $date->format('j') }}</th>
                            @endforeach
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($matrixRows as $row)
                            <tr>
                                <td class="name-col">{{ $row['name'] }}</td>
                                @foreach ($row['cells'] as $cell)
                                    <td><span class="cell-dot {{ $cell['class'] }}">{{ $cell['code'] }}</span></td>
                                @endforeach
                                <td>{{ $row['presentCount'] }}</td>
                                <td>{{ $row['notPresentCount'] }}</td>
                                <td>{{ number_format((float) $row['allowance'], 0, ',', '.') }}</td>
                            </tr>
                        @empty
                            <tr>
                                <td class="name-col" colspan="{{ $dates->count() + 4 }}">Tidak ada data pada filter ini.</td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </td>
            <td class="legend-wrap">
                <div class="legend">
                    <h2>Warna Kehadiran</h2>
                    <table>
                        @foreach ($payload['legend'] as $legend)
                            <tr>
                                <td style="width: 24px;"><div class="legend-swatch {{ $legend['class'] }}">{{ $legend['code'] }}</div></td>
                                <td>{{ strtolower($legend['label']) }}</td>
                            </tr>
                        @endforeach
                    </table>
                </div>
            </td>
        </tr>
    </table>

    <div class="footer">Generated by Kalbe Internship Monitoring</div>
</body>
</html>
